udo: required

services:
    - docker

dist: xenial

language: python

python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - python -m pytest -v

after_success:
    - sh .travis/deploy_dockerhub.sh