version: '3'
services: 
    flask-app:
        build: ./flask-app
        container_name: basic-flask-app
        image: kryvokhyzha/basic-flask-app:latest
        command: gunicorn -b 0.0.0.0:5000 run:app --workers=1 --threads=1 --reload
        environment: 
            - FLASK_APP=run.py
            - FLASK_DEBUG=1
            - PYTHONUNBUFFERED=TRUE
        expose: 
            - "5000"
        volumes: 
            - ./flask-app:/home/root
    nginx:
        build: ./nginx
        ports: 
            - "80:80"
        container_name: nginx-flask
        volumes: 
            - ./flask-app:/home/root
