version: '3'
services: 
    flask-app:
        build: .
        command: gunicorn -b 0.0.0.0:5000 run:app --workers=1 --threads=1 --reload
        environment: 
            - FLASK_APP=run.py
            - FLASK_DEBUG=1
            - PYTHONUNBUFFERED=TRUE
        ports: 
            - "5000:5000"
        volumes: 
            - ./:/root